<table border="1">
    <tr>
        <td>id</td>
        <td>{$process->getId()}</td>
    </tr>
    <tr>
        <td>pid</td>
        <td>{$process->getPid()}</td>
    </tr>
    <tr>
        <td>module</td>
        <td>{$process->getModule()}</td>
    </tr>
    <tr>
        <td>action</td>
        <td>{$process->getAction()}</td>
    </tr>
    <tr>
        <td>user_id</td>
        <td>{$process->getUserId()}</td>
    </tr>
    <tr>
        <td>name</td>
        <td>{$process->getName()}</td>
    </tr>
    <tr>
        <td>status</td>
        <td>{$process->getStatus()}</td>
    </tr>
    <tr>
        <td>percent</td>
        <td>{$process->getPercent()}</td>
    </tr>
</table>